version: '2.2'
services:
  troubleshootingapplication-1.0:
    image: "divyabhaarathy/troubleshootingtool-0.0.1"
    ports:
      - "4444:4444"
    networks:
      - elastic
    environment:
      - ElasticsearchHost=${ElasticsearchHost}

networks:
  elastic:
