FROM openjdk:8
ADD troubleshooting/TroubleshootingApplication/build/libs/troubleshootingapplication-1.0.jar troubleshootingapplication-1.0.jar
EXPOSE 4343
ENTRYPOINT ["java","-jar","troubleshootingapplication-1.0.jar"]
