pipeline {
  environment {
    registry = 'divyabhaarathy/troubleshootingapplication-1.0'
    registryCredential = 'dockerhub'
  }
  agent any
  stages {
    stage('Cloning Git') {
      steps {
        git 'https://github.com/divyabharathik/apimanagement.git'
      }
    }
    stage('Building image') {
      steps{
        sh "docker build -f Dockerfile -t troubleshootingapplication-1.0 ."
      }
    }
  }
}
